### ISSUE TITLE
Application don't shows transactions information after authorization

### ISSUE THREAD

**Issue by blink2004** [palatin/PayDayBank#3]
Hi!
Thanks for demo app! Interested job.

I have installed application and authorized with demo credentials. There are total income and expend without transactions details. I refreshed window (swiped down) and nothing changed. 

After that closed the app and relaunched it again. I couldn't type any key in email and password fields. The application didn't responded. 

Can you look at this case?

OS: Android 6.0.1

**Comment by palatin** [comment]
Hello, thank you for your response and interest in my work! 
It was a test assignment while I was trying to get a job. The employer provided a local server API written in Node Js with test data from which the application fetches transactions. I had to provide a dummy data repository and use it in di (Hilt) for this demo but unfortunately running out of time. I will investigate the unresponsive UI issue asap.

**Comment by palatin** [comment]
I think it because I didn't handle biometric exception here:
https://github.com/palatin/PayDayBank/blob/d3debe7ad53d00870b98638ab0c67ddb121b48d9/app/src/main/java/com/payday/paydaybank/auth/crypto/BioAuthenticator.kt#L37-L39
So coroutines will never ended while UI waits for a result through the channel.
